eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka"
#spring.main.web-application-type=reactive
server:
  port: 8082
  #specify prefix to all controller
  servlet: contextPath=/ope
  session:
    cookie:
      name: UISESSION
spring:
  application:
    name: ope
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    jpa:
#      generate-ddl: true
#    password: Asdfg13092@
#    url: "jdbc:mysql://localhost:3306/spring-security-users"
#    username: root
  security:
    oauth2:
      client:
        registration:
          custom-client:
            client-id: clientId
            client-secret: secret
            client-name: Auth Server
            scope: user_info
            provider: custom-provider
            redirect-uri-template: http://localhost:8082/login/oauth2/code/
            client-authentication-method: basic
            authorization-grant-type: authorization_code
        provider:
          custom-provider:
            token-uri: http://localhost:9000/auth/oauth/token
            authorization-uri: http://localhost:9000/auth/oauth/authorize
            user-info-uri: http://localhost:9000/auth/user/me
            user-name-attribute: email
